version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn tradewar.api.server:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SIMULATION_YEARS=5
      - SIMULATION_STEPS_PER_YEAR=4
      - RANDOM_SEED=42
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run tradewar/visualization/dashboard.py
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - API_HOST=api
      - API_PORT=8000
    depends_on:
      - api

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis-data:
